export { themeConfig } from './themeConfig'
export { default as HeroSection } from './HeroSection'
export { default as AboutSection } from './AboutSection'
export { default as ServicesSection } from './ServicesSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as ContactSection } from './ContactSection'
export { default as FooterSection } from './FooterSection'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
